(deftheme gotham
  "Created 2020-12-23.")

(custom-theme-set-faces
 'gotham
 '(button ((((type graphic)) :foreground "#245361" :box t) (((type tty)) :foreground "brightyellow" :box t)))
 '(shadow ((((type graphic)) :foreground "#245361") (((type tty)) :foreground "brightyellow")))
 '(highlight ((((type graphic)) :background "#091f2e") (((type tty)) :background "brightgreen")))
 '(link ((((type graphic)) :foreground "#d26937" :underline t) (((type tty)) :foreground "brightred" :underline t)))
 '(link-visited ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(cursor ((((type graphic)) :background "#99d1ce") (((type tty)) :background "white")))
 '(region ((((type graphic)) :foreground unspecified :background "#0a3749") (((type tty)) :foreground unspecified :background "brightblue")))
 '(secondary-selection ((((type graphic)) :foreground unspecified :background "#4e5166") (((type tty)) :foreground unspecified :background "magenta")))
 '(fringe ((((type graphic)) :foreground "#99d1ce" :background "#11151c") (((type tty)) :foreground "white" :background "brightblack")))
 '(vertical-border ((((type graphic)) :foreground "#245361") (((type tty)) :foreground "brightyellow")))
 '(tooltip ((((type graphic)) :foreground "#99d1ce" :background "#0c1014") (((type tty)) :foreground "white" :background "black")))
 '(trailing-whitespace ((((type graphic)) :background "#c23127") (((type tty)) :background "red")))
 '(escape-glyph ((((type graphic)) :foreground "#d26937" :weight bold) (((type tty)) :foreground "brightred" :weight bold)))
 '(font-lock-builtin-face ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(font-lock-comment-face ((((type graphic)) :foreground "#245361") (((type tty)) :foreground "brightyellow")))
 '(font-lock-comment-delimiter-face ((((type graphic)) :foreground "#245361") (((type tty)) :foreground "brightyellow")))
 '(font-lock-constant-face ((((type graphic)) :foreground "#33859e" :weight bold) (((type tty)) :foreground "cyan" :weight bold)))
 '(font-lock-doc-face ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(font-lock-function-name-face ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(font-lock-keyword-face ((((type graphic)) :foreground "#195466" :weight bold) (((type tty)) :foreground "blue" :weight bold)))
 '(font-lock-negation-char-face ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(font-lock-preprocessor-face ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(font-lock-regexp-grouping-construct ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(font-lock-regexp-grouping-backslash ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(font-lock-string-face ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(font-lock-type-face ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(font-lock-variable-name-face ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(font-lock-warning-face ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(error ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(success ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(warning ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(match ((((type graphic)) :background "#245361") (((type tty)) :background "brightyellow")))
 '(isearch ((t nil)))
 '(isearch-fail ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(lazy-highlight ((((type graphic)) :foreground "#091f2e" :background "#edb443") (((type tty)) :foreground "brightgreen" :background "yellow")))
 '(minibuffer-prompt ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(header-line ((((type graphic)) :foreground "#599cab" :background "#091f2e") (((type tty)) :foreground "brightcyan" :background "brightgreen")))
 '(menu ((((type graphic)) :background "#0a3749" :foreground "#99d1ce") (((type tty)) :background "brightblue" :foreground "white")))
 '(mode-line ((((type graphic)) :foreground "#599cab" :background "#091f2e" :box nil) (((type tty)) :foreground "brightcyan" :background "brightgreen" :box nil)))
 '(mode-line-inactive ((((type graphic)) :foreground "#245361" :background "#11151c" :box nil) (((type tty)) :foreground "brightyellow" :background "brightblack" :box nil)))
 '(mode-line-highlight ((((type graphic)) :foreground "#99d1ce") (((type tty)) :foreground "white")))
 '(mode-line-buffer-id ((((type graphic)) :weight bold) (((type tty)) :weight bold)))
 '(custom-button ((((type graphic)) :foreground "#245361" :box t) (((type tty)) :foreground "brightyellow" :box t)))
 '(custom-button-mouse ((((type graphic)) :foreground "#599cab" :box t) (((type tty)) :foreground "brightcyan" :box t)))
 '(custom-group-tag ((((type graphic)) :inherit fixed-pitch :foreground "#888ca6") (((type tty)) :inherit fixed-pitch :foreground "brightmagenta")))
 '(custom-state ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(compilation-mode-line-fail ((((type graphic)) :foreground unspecified :inherit compilation-error) (((type tty)) :foreground unspecified :inherit compilation-error)))
 '(compilation-mode-line-exit ((((type graphic)) :foreground unspecified :inherit compilation-info) (((type tty)) :foreground unspecified :inherit compilation-info)))
 '(diff-added ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(diff-changed ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(diff-header ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(diff-file-header ((((type graphic)) :weight bold) (((type tty)) :weight bold)))
 '(diff-refine-added ((((type graphic)) :background "#0a3749") (((type tty)) :background "brightblue")))
 '(diff-refine-removed ((((type graphic)) :background "#0a3749") (((type tty)) :background "brightblue")))
 '(diff-removed ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(eldoc-highlight-function-argument ((((type graphic)) :foreground "#d26937" :weight bold) (((type tty)) :foreground "brightred" :weight bold)))
 '(eshell-prompt ((((type graphic)) :foreground "#edb443" :weight bold) (((type tty)) :foreground "yellow" :weight bold)))
 '(eshell-ls-archive ((((type graphic)) :foreground "#888ca6") (((type tty)) :foreground "brightmagenta")))
 '(eshell-ls-backup ((((type graphic)) :foreground "#4e5166" :weight bold) (((type tty)) :foreground "magenta" :weight bold)))
 '(eshell-ls-clutter ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(eshell-ls-directory ((((type graphic)) :foreground "#33859e" :weight bold) (((type tty)) :foreground "cyan" :weight bold)))
 '(eshell-ls-executable ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(eshell-ls-missing ((((type graphic)) :foreground "#c23127" :weight bold) (((type tty)) :foreground "red" :weight bold)))
 '(eshell-ls-product ((((type graphic)) :foreground "#0a3749") (((type tty)) :foreground "brightblue")))
 '(eshell-ls-readonly ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(eshell-ls-special ((((type graphic)) :foreground "#d26937" :weight bold) (((type tty)) :foreground "brightred" :weight bold)))
 '(eshell-ls-symlink ((((type graphic)) :foreground "#195466" :weight bold) (((type tty)) :foreground "blue" :weight bold)))
 '(eshell-ls-unreadable ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(flymake-error ((((type graphic)) :underline (:style wave :color "#c23127")) (((type tty)) :underline (:style wave :color "red"))))
 '(flymake-warning ((((type graphic)) :underline (:style wave :color "#d26937")) (((type tty)) :underline (:style wave :color "brightred"))))
 '(flyspell-duplicate ((((type graphic)) :underline (:style wave :color "#d26937")) (((type tty)) :underline (:style wave :color "brightred"))))
 '(flyspell-incorrect ((((type graphic)) :underline (:style wave :color "#c23127")) (((type tty)) :underline (:style wave :color "red"))))
 '(gnus-group-mail-1 ((((type graphic)) :foreground "#2aa889" :weight bold) (((type tty)) :foreground "green" :weight bold)))
 '(gnus-group-mail-1-empty ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(gnus-group-mail-2 ((((type graphic)) :foreground "#33859e" :weight bold) (((type tty)) :foreground "cyan" :weight bold)))
 '(gnus-group-mail-2-empty ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(gnus-group-mail-3 ((((type graphic)) :foreground "#4e5166" :weight bold) (((type tty)) :foreground "magenta" :weight bold)))
 '(gnus-group-mail-3-empty ((((type graphic)) :foreground "#4e5166") (((type tty)) :foreground "magenta")))
 '(gnus-group-mail-low ((((type graphic)) :foreground "#599cab" :weight bold) (((type tty)) :foreground "brightcyan" :weight bold)))
 '(gnus-group-mail-low-empty ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(gnus-group-news-1 ((((type graphic)) :foreground "#245361" :weight bold) (((type tty)) :foreground "brightyellow" :weight bold)))
 '(gnus-group-news-1-empty ((((type graphic)) :foreground "#245361") (((type tty)) :foreground "brightyellow")))
 '(gnus-group-news-2 ((((type graphic)) :foreground "#888ca6" :weight bold) (((type tty)) :foreground "brightmagenta" :weight bold)))
 '(gnus-group-news-2-empty ((((type graphic)) :foreground "#888ca6") (((type tty)) :foreground "brightmagenta")))
 '(gnus-group-news-3 ((((type graphic)) :foreground "#d3ebe9" :weight bold) (((type tty)) :foreground "brightwhite" :weight bold)))
 '(gnus-group-news-3-empty ((((type graphic)) :foreground "#d3ebe9") (((type tty)) :foreground "brightwhite")))
 '(gnus-group-news-4 ((((type graphic)) :foreground "#4e5166" :weight bold) (((type tty)) :foreground "magenta" :weight bold)))
 '(gnus-group-news-5 ((((type graphic)) :foreground "#33859e" :weight bold) (((type tty)) :foreground "cyan" :weight bold)))
 '(gnus-group-news-5-empty ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(gnus-group-news-6 ((((type graphic)) :foreground "#2aa889" :weight bold) (((type tty)) :foreground "green" :weight bold)))
 '(gnus-group-news-6-empty ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(gnus-group-news-low ((((type graphic)) :foreground "#195466" :weight bold) (((type tty)) :foreground "blue" :weight bold)))
 '(gnus-group-news-low-empty ((((type graphic)) :foreground "#195466") (((type tty)) :foreground "blue")))
 '(gnus-splash ((((type graphic)) :foreground "#99d1ce") (((type tty)) :foreground "white")))
 '(gnus-summary-cancelled ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(gnus-summary-high-ancient ((((type graphic)) :foreground "#195466" :weight bold) (((type tty)) :foreground "blue" :weight bold)))
 '(gnus-summary-high-read ((((type graphic)) :foreground "#2aa889" :weight bold) (((type tty)) :foreground "green" :weight bold)))
 '(gnus-summary-high-ticked ((((type graphic)) :foreground "#d3ebe9" :weight bold) (((type tty)) :foreground "brightwhite" :weight bold)))
 '(gnus-summary-high-undownloaded ((((type graphic)) :foreground "#599cab" :weight bold) (((type tty)) :foreground "brightcyan" :weight bold)))
 '(gnus-summary-low-ancient ((((type graphic)) :inherit italic :foreground "#195466") (((type tty)) :inherit italic :foreground "blue")))
 '(gnus-summary-low-read ((((type graphic)) :inherit italic :foreground "#2aa889") (((type tty)) :inherit italic :foreground "green")))
 '(gnus-summary-low-ticked ((((type graphic)) :inherit italic :foreground "#d3ebe9") (((type tty)) :inherit italic :foreground "brightwhite")))
 '(gnus-summary-low-undownloaded ((((type graphic)) :inherit italic :foreground "#245361") (((type tty)) :inherit italic :foreground "brightyellow")))
 '(gnus-summary-normal-ancient ((((type graphic)) :foreground "#195466") (((type tty)) :foreground "blue")))
 '(gnus-summary-normal-read ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(gnus-summary-normal-ticked ((((type graphic)) :foreground "#d3ebe9") (((type tty)) :foreground "brightwhite")))
 '(gnus-summary-normal-undownloaded ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(gnus-summary-normal-unread ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(Info-quoted ((((type graphic)) :inherit font-lock-constant-face) (((type tty)) :inherit font-lock-constant-face)))
 '(info-menu-header ((((type graphic)) :foreground "#2aa889" :weight bold :height 1.4) (((type tty)) :foreground "green" :weight bold :height 1.4)))
 '(info-menu-star ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(info-node ((((type graphic)) :inherit italic :foreground "#99d1ce" :weight bold) (((type tty)) :inherit italic :foreground "white" :weight bold)))
 '(info-title-1 ((((type graphic)) :weight bold :height 1.6) (((type tty)) :weight bold :height 1.6)))
 '(info-title-2 ((((type graphic)) :weight bold :height 1.4) (((type tty)) :weight bold :height 1.4)))
 '(info-title-3 ((((type graphic)) :weight bold :height 1.2) (((type tty)) :weight bold :height 1.2)))
 '(info-title-4 ((((type graphic)) :weight bold) (((type tty)) :weight bold)))
 '(message-cited-text-1 ((((type graphic)) :foreground "#195466") (((type tty)) :foreground "blue")))
 '(message-header-cc ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(message-header-name ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(message-header-newsgroups ((((type graphic)) :inherit shadow) (((type tty)) :inherit shadow)))
 '(message-header-other ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(message-header-subject ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(message-header-to ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(message-header-xheader ((((type graphic)) :inherit shadow) (((type tty)) :inherit shadow)))
 '(message-mml ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(message-separator ((((type graphic)) :foreground "#195466") (((type tty)) :foreground "blue")))
 '(outline-1 ((((type graphic)) :foreground "#4e5166") (((type tty)) :foreground "magenta")))
 '(outline-2 ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(outline-3 ((((type graphic)) :foreground "#888ca6") (((type tty)) :foreground "brightmagenta")))
 '(outline-4 ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(outline-5 ((((type graphic)) :foreground "#4e5166") (((type tty)) :foreground "magenta")))
 '(outline-6 ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(outline-7 ((((type graphic)) :foreground "#888ca6") (((type tty)) :foreground "brightmagenta")))
 '(outline-8 ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(pulse-highlight-start-face ((((type graphic)) :background "#245361") (((type tty)) :background "brightyellow")))
 '(reb-match-0 ((((type graphic)) :foreground "#0c1014" :background "#99d1ce") (((type tty)) :foreground "black" :background "white")))
 '(reb-match-1 ((((type graphic)) :foreground "#0c1014" :background "#2aa889") (((type tty)) :foreground "black" :background "green")))
 '(reb-match-2 ((((type graphic)) :foreground "#0c1014" :background "#edb443") (((type tty)) :foreground "black" :background "yellow")))
 '(reb-match-3 ((((type graphic)) :foreground "#0c1014" :background "#33859e") (((type tty)) :foreground "black" :background "cyan")))
 '(speedbar-button-face ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(speedbar-directory-face ((((type graphic)) :foreground "#599cab" :weight bold) (((type tty)) :foreground "brightcyan" :weight bold)))
 '(speedbar-file-face ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(speedbar-highlight-face ((((type graphic)) :inherit highlight) (((type tty)) :inherit highlight)))
 '(speedbar-selected-face ((((type graphic)) :inherit highlight) (((type tty)) :inherit highlight)))
 '(speedbar-separator-face ((((type graphic)) :background "#195466" :overline t) (((type tty)) :background "blue" :overline t)))
 '(speedbar-tag-face ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(show-paren-match ((((type graphic)) :foreground "#091f2e" :background "#d26937" :inverse-video nil) (((type tty)) :foreground "brightgreen" :background "brightred" :inverse-video nil)))
 '(show-paren-mismatch ((((type graphic)) :foreground "#091f2e" :background "#c23127" :inverse-video nil) (((type tty)) :foreground "brightgreen" :background "red" :inverse-video nil)))
 '(term-color-black ((((type graphic)) :foreground "#11151c" :background "#11151c") (((type tty)) :foreground "brightblack" :background "brightblack")))
 '(term-color-red ((((type graphic)) :foreground "#c23127" :background "#c23127") (((type tty)) :foreground "red" :background "red")))
 '(term-color-green ((((type graphic)) :foreground "#2aa889" :background "#2aa889") (((type tty)) :foreground "green" :background "green")))
 '(term-color-yellow ((((type graphic)) :foreground "#edb443" :background "#edb443") (((type tty)) :foreground "yellow" :background "yellow")))
 '(term-color-blue ((((type graphic)) :foreground "#195466" :background "#195466") (((type tty)) :foreground "blue" :background "blue")))
 '(term-color-magenta ((((type graphic)) :foreground "#888ca6" :background "#888ca6") (((type tty)) :foreground "brightmagenta" :background "brightmagenta")))
 '(term-color-cyan ((((type graphic)) :foreground "#33859e" :background "#33859e") (((type tty)) :foreground "cyan" :background "cyan")))
 '(term-color-white ((((type graphic)) :foreground "#99d1ce" :background "#99d1ce") (((type tty)) :foreground "white" :background "white")))
 '(widget-button-pressed ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(widget-documentation ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(widget-field ((((type graphic)) :background "#245361") (((type tty)) :background "brightyellow")))
 '(widget-single-line-field ((((type graphic)) :inherit widget-field) (((type tty)) :inherit widget-field)))
 '(which-func ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(whitespace-empty ((((type graphic)) :foreground "#d3ebe9" :background "#33859e") (((type tty)) :foreground "brightwhite" :background "cyan")))
 '(whitespace-hspace ((((type graphic)) :foreground "#d3ebe9" :background "#888ca6") (((type tty)) :foreground "brightwhite" :background "brightmagenta")))
 '(whitespace-indentation ((((type graphic)) :background "#edb443") (((type tty)) :background "yellow")))
 '(whitespace-line ((((type graphic)) :foreground "#99d1ce" :background "#4e5166") (((type tty)) :foreground "white" :background "magenta")))
 '(whitespace-newline ((((type graphic)) :foreground "#0a3749") (((type tty)) :foreground "brightblue")))
 '(whitespace-space ((((type graphic)) :foreground "#d3ebe9" :background "#091f2e") (((type tty)) :foreground "brightwhite" :background "brightgreen")))
 '(whitespace-space-after-tab ((((type graphic)) :foreground "#d3ebe9" :background "#d26937") (((type tty)) :foreground "brightwhite" :background "brightred")))
 '(whitespace-space-before-tab ((((type graphic)) :foreground "#d3ebe9" :background "#d26937") (((type tty)) :foreground "brightwhite" :background "brightred")))
 '(whitespace-tab ((((type graphic)) :background "#0a3749") (((type tty)) :background "brightblue")))
 '(whitespace-trailing ((((type graphic)) :foreground "#d3ebe9" :background "#c23127") (((type tty)) :foreground "brightwhite" :background "red")))
 '(aw-background-face ((((type graphic)) :foreground "#0a3749") (((type tty)) :foreground "brightblue")))
 '(aw-leading-char-face ((((type graphic)) :foreground "#d3ebe9" :background "#0a3749") (((type tty)) :foreground "brightwhite" :background "brightblue")))
 '(anzu-mode-line ((((type graphic)) :foreground "#d26937" :weight bold) (((type tty)) :foreground "brightred" :weight bold)))
 '(anzu-mode-line-no-match ((((type graphic)) :foreground "#c23127" :weight bold) (((type tty)) :foreground "red" :weight bold)))
 '(anzu-replace-highlight ((((type graphic)) :foreground "#99d1ce" :background "#245361") (((type tty)) :foreground "white" :background "brightyellow")))
 '(anzu-match-1 ((((type graphic)) :foreground "#0c1014" :background "#2aa889") (((type tty)) :foreground "black" :background "green")))
 '(anzu-match-2 ((((type graphic)) :foreground "#0c1014" :background "#edb443") (((type tty)) :foreground "black" :background "yellow")))
 '(anzu-match-3 ((((type graphic)) :foreground "#0c1014" :background "#33859e") (((type tty)) :foreground "black" :background "cyan")))
 '(anzu-replace-to ((((type graphic)) :foreground "#edb443" :background "#0a3749") (((type tty)) :foreground "yellow" :background "brightblue")))
 '(font-latex-bold-face ((((type graphic)) :inherit bold) (((type tty)) :inherit bold)))
 '(font-latex-doctex-documentation-face ((((type graphic)) :inherit highlight) (((type tty)) :inherit highlight)))
 '(font-latex-doctex-preprocessor-face ((((type graphic)) :inherit highlight :foreground "#c23127") (((type tty)) :inherit highlight :foreground "red")))
 '(font-latex-italic-face ((((type graphic)) :inherit italic) (((type tty)) :inherit italic)))
 '(font-latex-math-face ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(font-latex-sectioning-0-face ((((type graphic)) :inherit bold :foreground "#edb443") (((type tty)) :inherit bold :foreground "yellow")))
 '(font-latex-sectioning-1-face ((((type graphic)) :inherit bold :foreground "#edb443") (((type tty)) :inherit bold :foreground "yellow")))
 '(font-latex-sectioning-2-face ((((type graphic)) :inherit bold :foreground "#edb443") (((type tty)) :inherit bold :foreground "yellow")))
 '(font-latex-sectioning-3-face ((((type graphic)) :inherit bold :foreground "#edb443") (((type tty)) :inherit bold :foreground "yellow")))
 '(font-latex-sectioning-4-face ((((type graphic)) :inherit bold :foreground "#edb443") (((type tty)) :inherit bold :foreground "yellow")))
 '(font-latex-sectioning-5-face ((((type graphic)) :inherit bold :foreground "#edb443") (((type tty)) :inherit bold :foreground "yellow")))
 '(font-latex-sedate-face ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(font-latex-slide-title-face ((((type graphic)) :inherit bold :foreground "#d26937") (((type tty)) :inherit bold :foreground "brightred")))
 '(font-latex-string-face ((((type graphic)) :inherit font-lock-string-face) (((type tty)) :inherit font-lock-string-face)))
 '(font-latex-verbatim-face ((((type graphic)) :inherit font-lock-string-face) (((type tty)) :inherit font-lock-string-face)))
 '(font-latex-warning-face ((((type graphic)) :inherit warning) (((type tty)) :inherit warning)))
 '(avy-background-face ((((type graphic)) :foreground "#0a3749") (((type tty)) :foreground "brightblue")))
 '(avy-lead-face ((((type graphic)) :foreground "#d3ebe9" :background "#0a3749") (((type tty)) :foreground "brightwhite" :background "brightblue")))
 '(avy-lead-face-0 ((((type graphic)) :foreground "#0c1014" :background "#245361") (((type tty)) :foreground "black" :background "brightyellow")))
 '(avy-lead-face-1 ((((type graphic)) :foreground "#0c1014" :background "#888ca6") (((type tty)) :foreground "black" :background "brightmagenta")))
 '(avy-lead-face-2 ((((type graphic)) :foreground "#0c1014" :background "#2aa889") (((type tty)) :foreground "black" :background "green")))
 '(company-echo-common ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(company-preview ((((type graphic)) :inherit company-tooltip-selection) (((type tty)) :inherit company-tooltip-selection)))
 '(company-preview-common ((((type graphic)) :inherit company-preview :foreground "#edb443") (((type tty)) :inherit company-preview :foreground "yellow")))
 '(company-preview-search ((((type graphic)) :inherit company-preview) (((type tty)) :inherit company-preview)))
 '(company-scrollbar-bg ((((type graphic)) :background "#091f2e") (((type tty)) :background "brightgreen")))
 '(company-scrollbar-fg ((((type graphic)) :background "#245361") (((type tty)) :background "brightyellow")))
 '(company-tooltip ((((type graphic)) :foreground "#99d1ce" :background "#091f2e") (((type tty)) :foreground "white" :background "brightgreen")))
 '(company-tooltip-annotation ((((type graphic)) :inherit company-tooltip :foreground "#c23127") (((type tty)) :inherit company-tooltip :foreground "red")))
 '(company-tooltip-common ((((type graphic)) :background "#091f2e" :weight bold) (((type tty)) :background "brightgreen" :weight bold)))
 '(company-tooltip-common-selection ((((type graphic)) :foreground "#d3ebe9" :background "#245361" :weight bold) (((type tty)) :foreground "brightwhite" :background "brightyellow" :weight bold)))
 '(company-tooltip-mouse ((((type graphic)) :foreground "#d3ebe9" :background "#245361") (((type tty)) :foreground "brightwhite" :background "brightyellow")))
 '(company-tooltip-selection ((((type graphic)) :foreground "#d3ebe9" :background "#245361") (((type tty)) :foreground "brightwhite" :background "brightyellow")))
 '(diff-hl-change ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(diff-hl-delete ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(diff-hl-insert ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(flx-highlight-face ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(flycheck-error ((((type graphic)) :underline (:style wave :color "#c23127")) (((type tty)) :underline (:style wave :color "red"))))
 '(flycheck-info ((((type graphic)) :underline (:style wave :color "#2aa889")) (((type tty)) :underline (:style wave :color "green"))))
 '(flycheck-warning ((((type graphic)) :underline (:style wave :color "#d26937")) (((type tty)) :underline (:style wave :color "brightred"))))
 '(ivy-confirm-face ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(ivy-current-match ((((type graphic)) :foreground "#d3ebe9" :background "#0a3749") (((type tty)) :foreground "brightwhite" :background "brightblue")))
 '(ivy-cursor ((((type graphic)) :foreground "#d3ebe9" :background "#0a3749") (((type tty)) :foreground "brightwhite" :background "brightblue")))
 '(ivy-minibuffer-match-face-1 ((((type graphic)) :foreground "#0c1014" :background "#245361") (((type tty)) :foreground "black" :background "brightyellow")))
 '(ivy-minibuffer-match-face-2 ((((type graphic)) :foreground "#0c1014" :background "#888ca6") (((type tty)) :foreground "black" :background "brightmagenta")))
 '(ivy-minibuffer-match-face-3 ((((type graphic)) :foreground "#0c1014" :background "#2aa889") (((type tty)) :foreground "black" :background "green")))
 '(ivy-minibuffer-match-face-4 ((((type graphic)) :foreground "#0c1014" :background "#599cab") (((type tty)) :foreground "black" :background "brightcyan")))
 '(ivy-modified-buffer ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(ivy-remote ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(ivy-subdir ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(ivy-virtual ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-bisect-bad ((((type graphic)) :foreground "#11151c" :background "#c23127" :box (:color "#99d1ce")) (((type tty)) :foreground "brightblack" :background "red" :box (:color "white"))))
 '(magit-bisect-good ((((type graphic)) :foreground "#091f2e" :background "#2aa889" :box (:color "#d3ebe9")) (((type tty)) :foreground "brightgreen" :background "green" :box (:color "brightwhite"))))
 '(magit-bisect-skip ((((type graphic)) :foreground "#091f2e" :background "#edb443" :box (:color "#d3ebe9")) (((type tty)) :foreground "brightgreen" :background "yellow" :box (:color "brightwhite"))))
 '(magit-blame-heading ((((type graphic)) :inherit header-line) (((type tty)) :inherit header-line)))
 '(magit-branch-local ((((type graphic)) :foreground "#99d1ce") (((type tty)) :foreground "white")))
 '(magit-branch-remote ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-cherry-equivalent ((((type graphic)) :foreground "#888ca6") (((type tty)) :foreground "brightmagenta")))
 '(magit-cherry-unmatched ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(magit-diff-added ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-diff-added-highlight ((((type graphic)) :foreground "#2aa889" :weight bold) (((type tty)) :foreground "green" :weight bold)))
 '(magit-diff-base ((((type graphic)) :foreground "#195466") (((type tty)) :foreground "blue")))
 '(magit-diff-base-highlight ((((type graphic)) :foreground "#195466" :weight bold) (((type tty)) :foreground "blue" :weight bold)))
 '(magit-diff-context ((((type graphic)) :background "#11151c") (((type tty)) :background "brightblack")))
 '(magit-diff-context-highlight ((((type graphic)) :background "#11151c" :weight bold) (((type tty)) :background "brightblack" :weight bold)))
 '(magit-diff-file-heading-selection ((((type graphic)) :foreground "#d26937" :inherit magit-diff-file-heading-highlight) (((type tty)) :foreground "brightred" :inherit magit-diff-file-heading-highlight)))
 '(magit-diff-hunk-heading ((((type graphic)) :background "#091f2e") (((type tty)) :background "brightgreen")))
 '(magit-diff-hunk-heading-highlight ((((type graphic)) :background "#091f2e" :weight bold) (((type tty)) :background "brightgreen" :weight bold)))
 '(magit-diff-hunk-heading-selection ((((type graphic)) :foreground "#d26937" :inherit magit-diff-hunk-heading-highlight) (((type tty)) :foreground "brightred" :inherit magit-diff-hunk-heading-highlight)))
 '(magit-diff-lines-heading ((((type graphic)) :foreground "#091f2e" :background "#d26937") (((type tty)) :foreground "brightgreen" :background "brightred")))
 '(magit-diff-removed ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(magit-diff-removed-highlight ((((type graphic)) :foreground "#c23127" :weight bold) (((type tty)) :foreground "red" :weight bold)))
 '(magit-diffstat-added ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-diffstat-removed ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(magit-dimmed ((((type graphic)) :inherit shadow) (((type tty)) :inherit shadow)))
 '(magit-hash ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(magit-log-author ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(magit-log-date ((((type graphic)) :foreground "#888ca6") (((type tty)) :foreground "brightmagenta")))
 '(magit-log-graph ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(magit-process-ng ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(magit-process-ok ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-reflog-amend ((((type graphic)) :foreground "#888ca6") (((type tty)) :foreground "brightmagenta")))
 '(magit-reflog-checkout ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(magit-reflog-cherry-pick ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-reflog-commit ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-reflog-merge ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-reflog-other ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(magit-reflog-rebase ((((type graphic)) :foreground "#888ca6") (((type tty)) :foreground "brightmagenta")))
 '(magit-reflog-remote ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(magit-reflog-reset ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(magit-refname ((((type graphic)) :foreground "#4e5166") (((type tty)) :foreground "magenta")))
 '(magit-section-heading ((((type graphic)) :foreground "#edb443" :weight bold) (((type tty)) :foreground "yellow" :weight bold)))
 '(magit-section-heading-selection ((((type graphic)) :foreground "#d26937" :weight bold) (((type tty)) :foreground "brightred" :weight bold)))
 '(magit-section-highlight ((((type graphic)) :background "#091f2e") (((type tty)) :background "brightgreen")))
 '(magit-sequence-drop ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(magit-sequence-head ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(magit-sequence-part ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(magit-sequence-stop ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-signature-bad ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(magit-signature-good ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(magit-signature-untrusted ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(magit-tag ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(markdown-header-face-1 ((((type graphic)) :background "#091f2e") (((type tty)) :background "brightgreen")))
 '(markdown-header-face-2 ((((type graphic)) :background "#0a3749") (((type tty)) :background "brightblue")))
 '(markdown-header-face-3 ((((type graphic)) :background "#245361") (((type tty)) :background "brightyellow")))
 '(markdown-header-face-4 ((((type graphic)) :background "#091f2e") (((type tty)) :background "brightgreen")))
 '(markdown-header-face-5 ((((type graphic)) :background "#0a3749") (((type tty)) :background "brightblue")))
 '(markdown-header-face-6 ((((type graphic)) :background "#245361") (((type tty)) :background "brightyellow")))
 '(org-agenda-dimmed-todo-face ((((type graphic)) :inherit shadow) (((type tty)) :inherit shadow)))
 '(org-agenda-done ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(org-agenda-restriction-lock ((((type graphic)) :inherit highlight) (((type tty)) :inherit highlight)))
 '(org-agenda-structure ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(org-block ((((type graphic)) :inherit default) (((type tty)) :inherit default)))
 '(org-clock-overlay ((((type graphic)) :inherit secondary-selection) (((type tty)) :inherit secondary-selection)))
 '(org-column ((((type graphic)) :background "#091f2e") (((type tty)) :background "brightgreen")))
 '(org-column-title ((((type graphic)) :inherit org-column :underline t) (((type tty)) :inherit org-column :underline t)))
 '(org-date ((((type graphic)) :foreground "#33859e" :underline t) (((type tty)) :foreground "cyan" :underline t)))
 '(org-date-selected ((((type graphic)) :foreground "#091f2e" :background "#888ca6") (((type tty)) :foreground "brightgreen" :background "brightmagenta")))
 '(org-document-info ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(org-document-title ((((type graphic)) :weight bold) (((type tty)) :weight bold)))
 '(org-done ((((type graphic)) :foreground "#2aa889" :weight bold) (((type tty)) :foreground "green" :weight bold)))
 '(org-drawer ((((type graphic)) :foreground "#599cab") (((type tty)) :foreground "brightcyan")))
 '(org-ellipsis ((((type graphic)) :inherit shadow :weight bold) (((type tty)) :inherit shadow :weight bold)))
 '(org-footnote ((((type graphic)) :foreground "#599cab" :underline t) (((type tty)) :foreground "brightcyan" :underline t)))
 '(org-formula ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(org-headline-done ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(org-hide ((t (:foreground "gray6"))))
 '(org-latex-and-related ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(org-scheduled ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(org-scheduled-previously ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(org-scheduled-today ((((type graphic)) :inherit org-scheduled) (((type tty)) :inherit org-scheduled)))
 '(org-sexp-date ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(org-table ((((type graphic)) :foreground "#4e5166") (((type tty)) :foreground "magenta")))
 '(org-time-grid ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(org-todo ((((type graphic)) :foreground "#c23127" :weight bold) (((type tty)) :foreground "red" :weight bold)))
 '(org-upcoming-deadline ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(popup-face ((((type graphic)) :foreground "#99d1ce" :background "#091f2e") (((type tty)) :foreground "white" :background "brightgreen")))
 '(popup-isearch-match ((((type graphic)) :foreground "#d3ebe9" :background "#245361") (((type tty)) :foreground "brightwhite" :background "brightyellow")))
 '(popup-menu-mouse-face ((((type graphic)) :foreground "#d3ebe9" :background "#245361") (((type tty)) :foreground "brightwhite" :background "brightyellow")))
 '(popup-menu-selection-face ((((type graphic)) :foreground "#d3ebe9" :background "#245361") (((type tty)) :foreground "brightwhite" :background "brightyellow")))
 '(popup-scroll-bar-background-face ((((type graphic)) :background "#091f2e") (((type tty)) :background "brightgreen")))
 '(popup-scroll-bar-foreground-face ((((type graphic)) :background "#245361") (((type tty)) :background "brightyellow")))
 '(popup-summary-face ((((type graphic)) :foreground "#245361" :background "#091f2e") (((type tty)) :foreground "brightyellow" :background "brightgreen")))
 '(popup-tip-face ((((type graphic)) :foreground "#d3ebe9" :background "#245361") (((type tty)) :foreground "brightwhite" :background "brightyellow")))
 '(rainbow-delimiters-depth-1-face ((((type graphic)) :foreground "#99d1ce") (((type tty)) :foreground "white")))
 '(rainbow-delimiters-depth-2-face ((((type graphic)) :foreground "#33859e") (((type tty)) :foreground "cyan")))
 '(rainbow-delimiters-depth-3-face ((((type graphic)) :foreground "#d26937") (((type tty)) :foreground "brightred")))
 '(rainbow-delimiters-depth-4-face ((((type graphic)) :foreground "#888ca6") (((type tty)) :foreground "brightmagenta")))
 '(rainbow-delimiters-depth-5-face ((((type graphic)) :foreground "#2aa889") (((type tty)) :foreground "green")))
 '(rainbow-delimiters-depth-6-face ((((type graphic)) :foreground "#195466") (((type tty)) :foreground "blue")))
 '(rainbow-delimiters-depth-7-face ((((type graphic)) :foreground "#edb443") (((type tty)) :foreground "yellow")))
 '(rainbow-delimiters-depth-8-face ((((type graphic)) :foreground "#4e5166") (((type tty)) :foreground "magenta")))
 '(rainbow-delimiters-depth-9-face ((((type graphic)) :foreground "#c23127") (((type tty)) :foreground "red")))
 '(rainbow-delimiters-unmatched-face ((((type graphic)) :foreground "#091f2e" :background "#99d1ce") (((type tty)) :foreground "brightgreen" :background "white")))
 '(sp-show-pair-match-face ((((type graphic)) :foreground "#091f2e" :background "#d26937") (((type tty)) :foreground "brightgreen" :background "brightred")))
 '(sp-show-pair-mismatch-face ((((type graphic)) :foreground "#091f2e" :background "#c23127") (((type tty)) :foreground "brightgreen" :background "red")))
 '(default ((((type graphic)) :foreground "#99d1ce" :background "#0c1014") (((type tty)) :foreground "white" :background "black"))))

(provide-theme 'gotham)
